### ISSUE TITLE
Cannot compile dev-lang/rust-1.16 -  error: undefined reference to 'LLVMInitializeNVPTXAsmPrinter'

### ISSUE THREAD

**Issue by saboya** [gentoo/gentoo-rust#246]
Hi. When updating world recently, rust-1.16 failed to compile for me, this is the end of the build.log:

```
info: now are following matches for librustc_plugin-*.so libraries:
x86_64-unknown-linux-gnu/stage1/lib64/rust-1.16.0/librustc_plugin-63283ac5.so
info: now are following matches for librustc_trans-*.so libraries:
x86_64-unknown-linux-gnu/stage0/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_trans-63283ac5.so
info: now are following matches for librustc_trans-*.rlib libraries:
x86_64-unknown-linux-gnu/stage0/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_trans-63283ac5.rlib
MATCHES=""; if [ -n "$MATCHES" ] ; then echo "warning: removing previous" \'librustc_trans-*.so\' "libraries:" $MATCHES; rm $MATCHES ; fi
cp x86_64-unknown-linux-gnu/stage0/lib/rustlib/x86_64-unknown-linux-gnu/lib/stamp.rustc_trans x86_64-unknown-linux-gnu/stage1/lib64/rust-1.16.0/stamp.rustc_trans
cp -R x86_64-unknown-linux-gnu/stage0/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_trans-*.so x86_64-unknown-linux-gnu/stage1/lib64/rust-1.16.0
info: now are following matches for librustc_trans-*.so libraries:
x86_64-unknown-linux-gnu/stage1/lib64/rust-1.16.0/librustc_trans-63283ac5.so
info: now are following matches for libproc_macro_plugin-*.so libraries:
x86_64-unknown-linux-gnu/stage0/lib/rustlib/x86_64-unknown-linux-gnu/lib/libproc_macro_plugin-63283ac5.so
info: now are following matches for libproc_macro_plugin-*.rlib libraries:
x86_64-unknown-linux-gnu/stage0/lib/rustlib/x86_64-unknown-linux-gnu/lib/libproc_macro_plugin-63283ac5.rlib
MATCHES=""; if [ -n "$MATCHES" ] ; then echo "warning: removing previous" \'libproc_macro_plugin-*.so\' "libraries:" $MATCHES; rm $MATCHES ; fi
cp x86_64-unknown-linux-gnu/stage0/lib/rustlib/x86_64-unknown-linux-gnu/lib/stamp.proc_macro_plugin x86_64-unknown-linux-gnu/stage1/lib64/rust-1.16.0/stamp.proc_macro_plugin
cp -R x86_64-unknown-linux-gnu/stage0/lib/rustlib/x86_64-unknown-linux-gnu/lib/libproc_macro_plugin-*.so x86_64-unknown-linux-gnu/stage1/lib64/rust-1.16.0
info: now are following matches for libproc_macro_plugin-*.so libraries:
x86_64-unknown-linux-gnu/stage1/lib64/rust-1.16.0/libproc_macro_plugin-63283ac5.so
info: now are following matches for librustc_typeck-*.so libraries:
x86_64-unknown-linux-gnu/stage0/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_typeck-63283ac5.so
info: now are following matches for librustc_typeck-*.rlib libraries:
x86_64-unknown-linux-gnu/stage0/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_typeck-63283ac5.rlib
MATCHES=""; if [ -n "$MATCHES" ] ; then echo "warning: removing previous" \'librustc_typeck-*.so\' "libraries:" $MATCHES; rm $MATCHES ; fi
MATCHES=""; if [ -n "$MATCHES" ] ; then echo "warning: removing previous" \'librustc_driver-*.so\' "libraries:" $MATCHES; rm $MATCHES ; fi
cp x86_64-unknown-linux-gnu/stage0/lib/rustlib/x86_64-unknown-linux-gnu/lib/stamp.rustc_typeck x86_64-unknown-linux-gnu/stage1/lib64/rust-1.16.0/stamp.rustc_typeck
MATCHES=""; if [ -n "$MATCHES" ] ; then echo "warning: removing previous" \'librustc_driver-*.rlib\' "libraries:" $MATCHES; rm $MATCHES ; fi
cp -R x86_64-unknown-linux-gnu/stage0/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_typeck-*.so x86_64-unknown-linux-gnu/stage1/lib64/rust-1.16.0
CFG_LLVM_LINKAGE_FILE=/var/tmp/portage/dev-lang/rust-1.16.0/work/rustc-1.16.0-src/x86_64-unknown-linux-gnu/rt/llvmdeps.rs LD_LIBRARY_PATH=/var/tmp/portage/dev-lang/rust-1.16.0/work/rustc-1.16.0-src/x86_64-unknown-linux-gnu/stage0/lib:/usr/lib:$LD_LIBRARY_PATH   x86_64-unknown-linux-gnu/stage0/bin/rustc --cfg stage0  -O --cfg rtopt -Cdebuginfo=1 -C prefer-dynamic --target=x86_64-unknown-linux-gnu   -L "x86_64-unknown-linux-gnu/rt" -L native="/usr/lib64"     --out-dir x86_64-unknown-linux-gnu/stage0/lib/rustlib/x86_64-unknown-linux-gnu/lib -C extra-filename=-63283ac5 -C metadata=63283ac5 src/librustc_driver/lib.rs
info: now are following matches for librustc_typeck-*.so libraries:
x86_64-unknown-linux-gnu/stage1/lib64/rust-1.16.0/librustc_typeck-63283ac5.so
info: now are following matches for librustc_driver-*.so libraries:
x86_64-unknown-linux-gnu/stage0/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_driver-63283ac5.so
info: now are following matches for librustc_driver-*.rlib libraries:
x86_64-unknown-linux-gnu/stage0/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_driver-63283ac5.rlib
LD_LIBRARY_PATH=/var/tmp/portage/dev-lang/rust-1.16.0/work/rustc-1.16.0-src/x86_64-unknown-linux-gnu/stage0/lib:/usr/lib:$LD_LIBRARY_PATH   x86_64-unknown-linux-gnu/stage0/bin/rustc --cfg stage0  -O --cfg rtopt -Cdebuginfo=1 -C prefer-dynamic --target=x86_64-unknown-linux-gnu  -L native="/usr/lib64" -o x86_64-unknown-linux-gnu/stage0/lib/rustlib/x86_64-unknown-linux-gnu/bin/rustc /var/tmp/portage/dev-lang/rust-1.16.0/work/rustc-1.16.0-src/src/driver/driver.rs --cfg rustc
MATCHES=""; if [ -n "$MATCHES" ] ; then echo "warning: removing previous" \'librustc_driver-*.so\' "libraries:" $MATCHES; rm $MATCHES ; fi
cp x86_64-unknown-linux-gnu/stage0/lib/rustlib/x86_64-unknown-linux-gnu/lib/stamp.rustc_driver x86_64-unknown-linux-gnu/stage1/lib64/rust-1.16.0/stamp.rustc_driver
cp -R x86_64-unknown-linux-gnu/stage0/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_driver-*.so x86_64-unknown-linux-gnu/stage1/lib64/rust-1.16.0
info: now are following matches for librustc_driver-*.so libraries:
x86_64-unknown-linux-gnu/stage1/lib64/rust-1.16.0/librustc_driver-63283ac5.so
error: linking with `cc` failed: exit code: 1
  |
  = note: "cc" "-Wl,--as-needed" "-Wl,-z,noexecstack" "-m64" "-L" "/var/tmp/portage/dev-lang/rust-1.16.0/work/rustc-1.16.0-src/x86_64-unknown-linux-gnu/stage0/lib/rustlib/x86_64-unknown-linux-gnu/lib" "x86_64-unknown-linux-gnu/stage0/lib/rustlib/x86_64-unknown-linux-gnu/bin/rustc.0.o" "-o" "x86_64-unknown-linux-gnu/stage0/lib/rustlib/x86_64-unknown-linux-gnu/bin/rustc" "-Wl,--gc-sections" "-pie" "-Wl,-O1" "-nodefaultlibs" "-L" "/usr/lib64" "-L" "/var/tmp/portage/dev-lang/rust-1.16.0/work/rustc-1.16.0-src/x86_64-unknown-linux-gnu/stage0/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-Wl,-Bstatic" "-Wl,-Bdynamic" "-L" "/var/tmp/portage/dev-lang/rust-1.16.0/work/rustc-1.16.0-src/x86_64-unknown-linux-gnu/stage0/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-l" "rustc_driver-63283ac5" "-L" "/var/tmp/portage/dev-lang/rust-1.16.0/work/rustc-1.16.0-src/x86_64-unknown-linux-gnu/stage0/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-l" "rustc_lint-63283ac5" "-L" "/var/tmp/portage/dev-lang/rust-1.16.0/work/rustc-1.16.0-src/x86_64-unknown-linux-gnu/stage0/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-l" "rustc_privacy-63283ac5" "-L" "/var/tmp/portage/dev-lang/rust-1.16.0/work/rustc-1.16.0-src/x86_64-unknown-linux-gnu/stage0/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-l" "rustc_save_analysis-63283ac5" "-L" "/var/tmp/portage/dev-lang/rust-1.16.0/work/rustc-1.16.0-src/x86_64-unknown-linux-gnu/stage0/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-l" "rustc_typeck-63283ac5" "-L" "/var/tmp/portage/dev-lang/rust-1.16.0/work/rustc-1.16.0-src/x86_64-unknown-linux-gnu/stage0/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-l" "rustc_borrowck-63283ac5" "-L" "/var/tmp/portage/dev-lang/rust-1.16.0/work/rustc-1.16.0-src/x86_64-unknown-linux-gnu/stage0/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-l" "rustc_mir-63283ac5" "-L" "/var/tmp/portage/dev-lang/rust-1.16.0/work/rustc-1.16.0-src/x86_64-unknown-linux-gnu/stage0/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-l" "rustc_passes-63283ac5" "-L" "/var/tmp/portage/dev-lang/rust-1.16.0/work/rustc-1.16.0-src/x86_64-unknown-linux-gnu/stage0/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-l" "rustc_resolve-63283ac5" "-L" "/var/tmp/portage/dev-lang/rust-1.16.0/work/rustc-1.16.0-src/x86_64-unknown-linux-gnu/stage0/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-l" "rustc_plugin-63283ac5" "-L" "/var/tmp/portage/dev-lang/rust-1.16.0/work/rustc-1.16.0-src/x86_64-unknown-linux-gnu/stage0/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-l" "rustc_metadata-63283ac5" "-L" "/var/tmp/portage/dev-lang/rust-1.16.0/work/rustc-1.16.0-src/x86_64-unknown-linux-gnu/stage0/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-l" "syntax_ext-63283ac5" "-L" "/var/tmp/portage/dev-lang/rust-1.16.0/work/rustc-1.16.0-src/x86_64-unknown-linux-gnu/stage0/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-l" "proc_macro-63283ac5" "-L" "/var/tmp/portage/dev-lang/rust-1.16.0/work/rustc-1.16.0-src/x86_64-unknown-linux-gnu/stage0/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-l" "rustc_trans-63283ac5" "-L" "/var/tmp/portage/dev-lang/rust-1.16.0/work/rustc-1.16.0-src/x86_64-unknown-linux-gnu/stage0/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-l" "rustc_const_eval-63283ac5" "-L" "/var/tmp/portage/dev-lang/rust-1.16.0/work/rustc-1.16.0-src/x86_64-unknown-linux-gnu/stage0/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-l" "rustc_platform_intrinsics-63283ac5" "-L" "/var/tmp/portage/dev-lang/rust-1.16.0/work/rustc-1.16.0-src/x86_64-unknown-linux-gnu/stage0/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-l" "rustc_incremental-63283ac5" "-L" "/var/tmp/portage/dev-lang/rust-1.16.0/work/rustc-1.16.0-src/x86_64-unknown-linux-gnu/stage0/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-l" "rustc-63283ac5" "-L" "/var/tmp/portage/dev-lang/rust-1.16.0/work/rustc-1.16.0-src/x86_64-unknown-linux-gnu/stage0/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-l" "rustc_const_math-63283ac5" "-L" "/var/tmp/portage/dev-lang/rust-1.16.0/work/rustc-1.16.0-src/x86_64-unknown-linux-gnu/stage0/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-l" "rustc_back-63283ac5" "-L" "/var/tmp/portage/dev-lang/rust-1.16.0/work/rustc-1.16.0-src/x86_64-unknown-linux-gnu/stage0/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-l" "syntax-63283ac5" "-L" "/var/tmp/portage/dev-lang/rust-1.16.0/work/rustc-1.16.0-src/x86_64-unknown-linux-gnu/stage0/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-l" "rustc_data_structures-63283ac5" "-L" "/var/tmp/portage/dev-lang/rust-1.16.0/work/rustc-1.16.0-src/x86_64-unknown-linux-gnu/stage0/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-l" "rustc_errors-63283ac5" "-L" "/var/tmp/portage/dev-lang/rust-1.16.0/work/rustc-1.16.0-src/x86_64-unknown-linux-gnu/stage0/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-l" "syntax_pos-63283ac5" "-L" "/var/tmp/portage/dev-lang/rust-1.16.0/work/rustc-1.16.0-src/x86_64-unknown-linux-gnu/stage0/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-l" "term-63283ac5" "-L" "/var/tmp/portage/dev-lang/rust-1.16.0/work/rustc-1.16.0-src/x86_64-unknown-linux-gnu/stage0/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-l" "log-63283ac5" "-L" "/var/tmp/portage/dev-lang/rust-1.16.0/work/rustc-1.16.0-src/x86_64-unknown-linux-gnu/stage0/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-l" "serialize-63283ac5" "-L" "/var/tmp/portage/dev-lang/rust-1.16.0/work/rustc-1.16.0-src/x86_64-unknown-linux-gnu/stage0/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-l" "rustc_llvm-63283ac5" "-L" "/var/tmp/portage/dev-lang/rust-1.16.0/work/rustc-1.16.0-src/x86_64-unknown-linux-gnu/stage0/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-l" "graphviz-63283ac5" "-L" "/var/tmp/portage/dev-lang/rust-1.16.0/work/rustc-1.16.0-src/x86_64-unknown-linux-gnu/stage0/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-l" "getopts-63283ac5" "-L" "/var/tmp/portage/dev-lang/rust-1.16.0/work/rustc-1.16.0-src/x86_64-unknown-linux-gnu/stage0/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-l" "fmt_macros-63283ac5" "-L" "/var/tmp/portage/dev-lang/rust-1.16.0/work/rustc-1.16.0-src/x86_64-unknown-linux-gnu/stage0/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-l" "arena-63283ac5" "-L" "/var/tmp/portage/dev-lang/rust-1.16.0/work/rustc-1.16.0-src/x86_64-unknown-linux-gnu/stage0/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-l" "flate-63283ac5" "-L" "/var/tmp/portage/dev-lang/rust-1.16.0/work/rustc-1.16.0-src/x86_64-unknown-linux-gnu/stage0/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-l" "std-63283ac5" "/var/tmp/portage/dev-lang/rust-1.16.0/work/rustc-1.16.0-src/x86_64-unknown-linux-gnu/stage0/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcompiler_builtins-63283ac5.rlib" "-l" "LLVMInterpreter" "-l" "LLVMMCJIT" "-l" "LLVMExecutionEngine" "-l" "LLVMRuntimeDyld" "-l" "LLVMipo" "-l" "LLVMVectorize" "-l" "LLVMLinker" "-l" "LLVMIRReader" "-l" "LLVMAsmParser" "-l" "LLVMX86Disassembler" "-l" "LLVMX86AsmParser" "-l" "LLVMX86CodeGen" "-l" "LLVMSelectionDAG" "-l" "LLVMAsmPrinter" "-l" "LLVMDebugInfoCodeView" "-l" "LLVMCodeGen" "-l" "LLVMTarget" "-l" "LLVMScalarOpts" "-l" "LLVMInstCombine" "-l" "LLVMInstrumentation" "-l" "LLVMTransformUtils" "-l" "LLVMBitWriter" "-l" "LLVMAnalysis" "-l" "LLVMProfileData" "-l" "LLVMX86Desc" "-l" "LLVMObject" "-l" "LLVMMCParser" "-l" "LLVMBitReader" "-l" "LLVMMCDisassembler" "-l" "LLVMX86Info" "-l" "LLVMX86AsmPrinter" "-l" "LLVMMC" "-l" "LLVMX86Utils" "-l" "LLVMCore" "-l" "LLVMSupport" "-l" "stdc++" "-l" "dl" "-l" "pthread" "-l" "gcc_s" "-l" "c" "-l" "m" "-l" "rt" "-l" "util"
  = note: /var/tmp/portage/dev-lang/rust-1.16.0/work/rustc-1.16.0-src/x86_64-unknown-linux-gnu/stage0/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_llvm-63283ac5.so: error: undefined reference to 'LLVMInitializeNVPTXAsmPrinter'
/var/tmp/portage/dev-lang/rust-1.16.0/work/rustc-1.16.0-src/x86_64-unknown-linux-gnu/stage0/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_llvm-63283ac5.so: error: undefined reference to 'LLVMInitializeNVPTXTarget'
/var/tmp/portage/dev-lang/rust-1.16.0/work/rustc-1.16.0-src/x86_64-unknown-linux-gnu/stage0/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_llvm-63283ac5.so: error: undefined reference to 'LLVMInitializeNVPTXTargetInfo'
/var/tmp/portage/dev-lang/rust-1.16.0/work/rustc-1.16.0-src/x86_64-unknown-linux-gnu/stage0/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_llvm-63283ac5.so: error: undefined reference to 'LLVMInitializeNVPTXTargetMC'
collect2: error: ld returned 1 exit status
```

Full build.log can be found [here](http://pastebin.com/DU1ZmkEh).

If you need more info about my system, just le me know!

**Comment by mpkh** [comment]
@saboya because of system-llvm, it should depend < 4 version I think, I'm a bit lazy for now to edit the ebuild =)

**Comment by saboya** [comment]
@mpkh < 4 or > 4? I have 3.9.1 installed (latest stable from portage).

**Comment by mpkh** [comment]
@saboya it needs some research. Well for now we know that it will not work with 3.9.1... not sure which version it does want under the hood.

**Comment by mpkh** [comment]
@saboya also a bit later 1.16 has been added to tree so possibly it will be sane to remove it for now from this overlay and redirect all the work to tree :)

**Comment by saboya** [comment]
Oh, my bad. Thanks for the heads-up.

**Comment by mpkh** [comment]
well I've added warning and removed flag from defaults https://github.com/gentoo/gentoo-rust/commit/685a85db09c87b8477a6061ba042189d91e2de51

**Comment by saboya** [comment]
Btw, I did a quick research and it seems there's effort to make rust compatible with llvm 4.0, and currently compiles with llvm 3.5-3.7. Don't take this as absolute truth tho, I just skimmed through stuff :)

**Comment by mpkh** [comment]
@saboya oh well... if you will manage to compile it with 3.7 - feel free to edit the ebuild, maybe only < 3.10 limitation was wrong and my current edit is even more worse...

**Comment by mpkh** [comment]
@saboya in tree they've removed system-llvm USE flag, and here I don't know which version to put there, there is an bugzilla issue about it but I've lost the link

**Comment by saboya** [comment]
Maybe it won't compile at all, it seems that there are changes in the llvm that rust uses that are not upstreamed yet, so it may be the case that system-llvm won't work until those are fixed.

I'll see if I can compile it with a lower version later. But I think removing the USE flag is correct, at least for now.

**Comment by mpkh** [comment]
@saboya yes, agreed, at the moment it's broken with it

**Comment by mpkh** [comment]
obsolete
